name: FoxBukkitBadge
main: com.foxelbox.foxbukkit.badge.FoxBukkitBadge
version: 1.0.0
commands:
  bmanage:
    description: Manages badges (add/remove/rename)
    permission: foxbukkit.badge.manage
    usage: /<command> add/rename/delete [ID] ...
  binfo:
    description: Displays badge info
    permission: foxbukkit.badge.info
    usage: /<command>
  badd:
    description: Assigns badges to users
    permission: foxbukkit.badge.assign
    usage: /<command> <user> <ID> <level|0>
  badges:
    description: Lists badges of user (or yourself)
    permission: foxbukkit.badge.badges
    usage: /<command> [target]
